source "https://rubygems.org"

gemspec

group :development do
  gem "chefstyle", "~> 2.2", ">= 2.2.2"
  gem "rake", "~> 13.0", ">= 13.0.6"
  gem "rspec", "~> 3.11"
end

group :test do
  gem "webmock", "~> 3.25", ">= 3.25.1"
  gem "pry"
  gem "byebug"
end
