require "bundler/gem_tasks"
require "rspec/core/rake_task"

RSpec::Core::RakeTask.new(:spec)

begin
  require "cookstyle/chefstyle"
  require "rubocop/rake_task"
  desc "Check Linting and code style."
  RuboCop::RakeTask.new(:style) do |task|
    task.options += %w{ --display-cop-names --no-color }
  end
rescue LoadError
  puts "Cookstyle gem is not installed. Run bundle install to install all dependencies."
end

task default: :spec
